name: Fedora 41 Build and RPM Package for InputActions

on:
  workflow_dispatch: # manual trigger
  push:
    branches: [ main ]
    paths-ignore: [ "**.md" ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ "**.md" ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:41
      options: --user root

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          dnf -y install git cmake extra-cmake-modules gcc-g++ qt6-qtbase-devel kwin-devel \
                        kf6-ki18n-devel kf6-kguiaddons-devel kf6-kcmutils-devel kf6-kconfigwidgets-devel \
                        qt6-qtbase kf6-kguiaddons kf6-ki18n wayland-devel yaml-cpp yaml-cpp-devel libepoxy-devel rpm-build
          git config --global --add safe.directory '*'

      - name: Build and Install yaml-cpp from Source
        run: |
          git clone https://github.com/jbeder/yaml-cpp.git
          cd yaml-cpp
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DYAML_CPP_BUILD_TESTS=OFF
          make -j$(nproc)
          make install

      - name: Configure CMake for InputActions
        run: |
          cmake -B ${{github.workspace}}/build \
                -DBUILD_KWIN_EFFECT=OFF \
                -DBUILD_TESTS=ON \
                -DCMAKE_INSTALL_PREFIX=/usr \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_PREFIX_PATH=/usr/local

      - name: Inject CPack into CMakeLists.txt
        run: |
          echo 'include(CPack)' >> ${{github.workspace}}/CMakeLists.txt

      - name: Build InputActions
        run: |
          cmake --build ${{github.workspace}}/build -j

      - name: Generate RPM Package
        run: |
          cd ${{github.workspace}}/build
          cpack -G RPM

      - name: Upload Built Files
        uses: actions/upload-artifact@v4
        with:
          name: inputactions-build
          path: ${{github.workspace}}/build/

      - name: Upload RPM Package
        uses: actions/upload-artifact@v4
        with:
          name: inputactions-rpm
          path: ${{github.workspace}}/build/*.rpm
