name: Build kwin-gestures on Fedora 41

on:
  workflow_dispatch: # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:41
    steps:
      - name: Install dependencies
        run: |
          dnf install -y git cmake extra-cmake-modules gcc-g++ qt6-qtbase-devel kwin-devel \
                         kf6-ki18n-devel kf6-kguiaddons-devel kf6-kcmutils-devel kf6-kconfigwidgets-devel \
                         qt6-qtbase kf6-kguiaddons kf6-ki18n wayland-devel yaml-cpp yaml-cpp-devel libepoxy-devel
      - name: Clone repo
        run: |
          git clone https://github.com/taj-ny/kwin-gestures
      - name: Build project
        run: |
          cd kwin-gestures
          mkdir build
          cd build
          cmake ../ -DCMAKE_INSTALL_PREFIX=/usr
          make -j$(nproc)
      - name: Upload built artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kwin-gestures-build
          path: kwin-gestures/build/
